FROM vbatts/slackware:14.2

#ARG ENCODING=UTF-8
#ARG LANG=C
#ARG TIMEZONE=Europe/Paris
#
#ENV LANG=$LANG.$ENCODING \
#    LANGUAGE=$LANG:$ENCODING \
#    LC_ALL=$LANG.$ENCODING \
#    TZ=$TIMEZONE

# slackpkg update && slackpkg install glibc-zoneinfo-2018e-noarch-2_slack14.2
#RUN set -eux \
#    && cp /usr/share/zoneinfo/$TIMEZONE /etc/localtime \
#    && echo "$TIMEZONE" >  /etc/timezone \
#    && date